version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
  build:
    commands:
      - composer install --optimize-autoloader --no-dev
      - sh $CODEBUILD_SRC_DIR/scripts/env
artifacts:
  files:
    - '**/*'
    